name: wf_test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12
            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  /usr/bin/git config --global --add safe.directory /home/runner/work/fastapi/fastapi
                  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
                  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
                  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
                  http.https://github.com/.extraheader
                  /usr/bin/git config --local --unset-all http.https://github.com/.extraheader
                  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
#            - name: Run tests
#              run: pytest tests
            - name: Run black
              run: black --diff --check main/
            - name: Run isort
              run: isort --check-only main/
            - name: Run flake8
              run: flake8 main/
            - name: Run mypy
              run: mypy main/
