name: wf_test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            # - name: Run flake8
            #   run: flake8 .
            - name: Run tests
              run: pytest tests
            - name: Run mypy
              run: mypy src/
            
    

# image: python:3.7


# stages:
#   - build
#   - test


# before-script:
#     - pip install -r requirements.txt

# unittest:
#   stage: test
#   script:
#     - pytest tests

# mypy:
#   stage: test
#   script:
#     - mypy src/

# black:
#   stage: test
#   script:
#     - black --diff --check src/

# isort:
#   stage: test
#   script:
#     - isort --check-only src/

# flask8:
#   stage: test
#   script:
#     - flake8 src/
