name: wf_test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12
            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
#            - name: Run tests
#              run: pytest tests
            - name: Run black
              run: black --diff --check main/
            - name: Run flake8
              run: flake8 main/
            - name: Run mypy
              run: mypy main/
            - name: Run isort
              run: isort --check-only main/
